### PR TITLE
Create HASwitchPlate_front_India_EU_86x86_blank.stl

### PR DESCRIPTION
**Pull request by ceaswaran**

### CODE REVIEW

**Review by aderusha — APPROVED** [review]

**Comment by ceaswaran** [comment]
how to add stl file to this
, please help

**Comment by bendikrb** [comment]
1 byte file? How did this get approved, I wonder?

**Comment by aderusha** [comment]
Good catch!  The file has been removed.

> How did this get approved, I wonder?

Poor review by the project maintainer would be the likely culprit :D

**Comment by bendikrb** [comment]
I guess it was this he was trying to upload: https://www.thingiverse.com/thing:3712046

**Comment by aderusha** [comment]
Hey thanks again!  That looks to be the right model and I've added it to the contrib folder.

**Pull request merged**
